### ISSUE TITLE
Which parts of the old plasma controls should remain?

### ISSUE THREAD

**Issue by azubieta** [plasma-extensions/plasma-widget-quick-controls#5]
Here are some screen shots of the current stage of the quick-controls widget, as you can see right now it is just a merge of the original plasma widgets. So the question which parts of the old plasma controls should remain?

![full](https://cloud.githubusercontent.com/assets/1138094/18250315/ef875186-7350-11e6-8c99-6a7821f723a0.png)
![devicedetails](https://cloud.githubusercontent.com/assets/1138094/18250357/2008e054-7351-11e6-96fb-c02587953a5a.png)
![networkconnectiondetails](https://cloud.githubusercontent.com/assets/1138094/18250363/23b713e2-7351-11e6-8004-96cf6c2ca61a.png)

**Comment by star-buck** [comment]
I think the usb is not needed.

What we could add is little shortcuts to bring up customization kcms like
wallpaper, icons, desktop theme, mouse cursor, window deco.

**Comment by UriHerrera** [comment]
@star-buck 

> What we could add is little shortcuts to bring up customization kcms like
> wallpaper, icons, desktop theme, mouse cursor, window deco.

Yeah that's going to be added (see #3 ). When the customization area isn't expanded (checkbox is unchecked) the only available drop down is _Select Look and Feel_. This allows the user to change everything on one click (of course, this is if the look and feel package the user is selecting does replace everything but that's up to the package creator and not us). However if the user would like to change each of the settings one-by-one the checkbox has to be checked.

This extends the customization area and shows the other options. Here the user can change each element separately: Plasma theme, Widget style, Color scheme, Window deco, etc... 

Of course each drop down would show whatever theme options are available for each available category.

> I think the usb is not needed.

If the external devices area is excluded there's _literally_ going to be **nothing** between the network connections and the customization area (see to #3 ). Since the space that was previously outlined there were the notifications which were split into another widget, the empty area was then replaced with the network area and the external devices area.

**Comment by azubieta** [comment]
This is how it looks with the devices removed and the network details hidden. Before continue with the Look and Feel quick controls coding I would like to confirm the design @star-buck @UriHerrera .
![new](https://cloud.githubusercontent.com/assets/1138094/18297305/8bf9dc28-747d-11e6-8a66-bb5c08f0cc68.png)

**Comment by UriHerrera** [comment]
Yep. Looks good to me. Though if the window is re-sizable what I commented above will happen.
